package net._01001111.simulant.words

import net._01001111.simulant.random.Randomizer

object Nouns extends Randomizer {
  lazy val all = List(
    Noun("air", "air"),
    Noun("animal", "animals"),
    Noun("atom", "atoms"),
    Noun("blood", "blood"),
    Noun("case", "cases"),
    Noun("cell", "cells"),
    Noun("child", "children"),
    Noun("cloud", "clouds"),
    Noun("company", "companies"),
    Noun("day", "days"),
    Noun("desert", "deserts"),
    Noun("door", "doors"),
    Noun("earth", "earths"),
    Noun("energy", "energies"),
    Noun("eye", "eyes"),
    Noun("fact", "facts"),
    Noun("fire", "fires"),
    Noun("government", "governments"),
    Noun("grass", "grasses"),
    Noun("group", "groups"),
    Noun("hand", "hands"),
    Noun("leaf", "leaves"),
    Noun("life", "lives"),
    Noun("light", "lights"),
    Noun("man", "men"),
    Noun("metal", "metals"),
    Noun("mind", "minds"),
    Noun("moon", "moons"),
    Noun("mountain", "mountains"),
    Noun("number", "numbers"),
    Noun("ocean", "oceans"),
    Noun("part", "parts"),
    Noun("particle", "particles"),
    Noun("person", "people"),
    Noun("place", "places"),
    Noun("point", "points"),
    Noun("problem", "problems"),
    Noun("rain", "rains"),
    Noun("rock", "rocks"),
    Noun("root", "roots"),
    Noun("sand", "sands"),
    Noun("sea", "seas"),
    Noun("soil", "soils"),
    Noun("star", "stars"),
    Noun("sun", "suns"),
    Noun("thing", "things"),
    Noun("thought", "thoughts"),
    Noun("time", "times"),
    Noun("tree", "trees"),
    Noun("voice", "voices"),
    Noun("water", "waters"),
    Noun("way", "ways"),
    Noun("week", "weeks"),
    Noun("woman", "women"),
    Noun("wood", "woods"),
    Noun("word", "words"),
    Noun("work", "works"),
    Noun("world", "worlds"),
    Noun("year", "years")
  )
  
  def one:Noun = random.select(all)
  def apply(n:Int):List[Noun] = random.select(all, n)
  
}